@node=node-1
@host=http://localhost:8080
@definition_key=1955877026946613248
### GetProcessDefinitions
GET {{host}}/v1/process-definitions
Accept: application/json

### DeployProcessDefinition
POST {{host}}/v1/process-definitions
Content-Type: application/xml

< pkg/bpmn/test-cases/service-task-input-output.bpmn

### StartProcessInstance
POST {{host}}/v1/process-instances
Content-Type: application/json

{
  "processDefinitionKey": "{{definition_key}}",
	"variables":{
	  "name": "Test name"
	}
}

### GetProcessInstances
GET {{host}}/v1/process-instances?processDefinitionKey={{definition_key}}&page=1

### ActivateJob
@job_type=input-task-1
POST {{host}}/v1/jobs/{{job_type}}/activate

### CompleteJob
POST {{host}}/v1/jobs
Content-Type: application/json

{
  "jobKey": "{{ActivateJob.response.body.$[0].key}}",
	"variables": {}
}

### Metrics
GET {{host}}/system/metrics

### Status
GET {{host}}/system/status

### StartCpuProfile
POST {{host}}/v1/test/{{node}}/start-cpu-profile

### StopCpuProfile
POST {{host}}/v1/test/{{node}}/stop-cpu-profile
