// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v7.34.1
// source: zenbpm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Values of ErrorResult.code. Zero means the error carries no code.
type JobStreamErrorCode int32

const (
	JobStreamErrorCode_JOB_STREAM_ERROR_CODE_UNSPECIFIED JobStreamErrorCode = 0
	// The lock lapsed, the job was completed or failed, or it was never delivered to this stream.
	JobStreamErrorCode_JOB_STREAM_ERROR_CODE_LOCK_NOT_HELD JobStreamErrorCode = 1
	// The job is currently locked for a different client id.
	JobStreamErrorCode_JOB_STREAM_ERROR_CODE_LOCK_HELD_BY_OTHER_CLIENT JobStreamErrorCode = 2
	// The leader of the job's partition could not be reached or has just changed. The
	// outcome is unconfirmed: the deadline may already have moved, and a leader change
	// forgets the lock. Retry the extension in a moment.
	JobStreamErrorCode_JOB_STREAM_ERROR_CODE_LEADER_UNAVAILABLE JobStreamErrorCode = 3
)

// Enum value maps for JobStreamErrorCode.
var (
	JobStreamErrorCode_name = map[int32]string{
		0: "JOB_STREAM_ERROR_CODE_UNSPECIFIED",
		1: "JOB_STREAM_ERROR_CODE_LOCK_NOT_HELD",
		2: "JOB_STREAM_ERROR_CODE_LOCK_HELD_BY_OTHER_CLIENT",
		3: "JOB_STREAM_ERROR_CODE_LEADER_UNAVAILABLE",
	}
	JobStreamErrorCode_value = map[string]int32{
		"JOB_STREAM_ERROR_CODE_UNSPECIFIED":               0,
		"JOB_STREAM_ERROR_CODE_LOCK_NOT_HELD":             1,
		"JOB_STREAM_ERROR_CODE_LOCK_HELD_BY_OTHER_CLIENT": 2,
		"JOB_STREAM_ERROR_CODE_LEADER_UNAVAILABLE":        3,
	}
)

func (x JobStreamErrorCode) Enum() *JobStreamErrorCode {
	p := new(JobStreamErrorCode)
	*p = x
	return p
}

func (x JobStreamErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStreamErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_zenbpm_proto_enumTypes[0].Descriptor()
}

func (JobStreamErrorCode) Type() protoreflect.EnumType {
	return &file_zenbpm_proto_enumTypes[0]
}

func (x JobStreamErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStreamErrorCode.Descriptor instead.
func (JobStreamErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_zenbpm_proto_rawDescGZIP(), []int{0}
}

type StreamSubscriptionRequest_Type int32

const (
	StreamSubscriptionRequest_TYPE_UNDEFINED   StreamSubscriptionRequest_Type = 0
	StreamSubscriptionRequest_TYPE_SUBSCRIBE   StreamSubscriptionRequest_Type = 1 // subscribe client to provided job_type
	StreamSubscriptionRequest_TYPE_UNSUBSCRIBE StreamSubscriptionRequest_Type = 2 // unsubscribe client from provided job_type
)

// Enum value maps for StreamSubscriptionRequest_Type.
var (
	StreamSubscriptionRequest_Type_name = map[int32]string{
		0: "TYPE_UNDEFINED",
		1: "TYPE_SUBSCRIBE",
		2: "TYPE_UNSUBSCRIBE",
	}
	StreamSubscriptionRequest_Type_value = map[string]int32{
		"TYPE_UNDEFINED":   0,
		"TYPE_SUBSCRIBE":   1,
		"TYPE_UNSUBSCRIBE": 2,
	}
)

func (x StreamSubscriptionRequest_Type) Enum() *StreamSubscriptionRequest_Type {
	p := new(StreamSubscriptionRequest_Type)
	*p = x
	return p
}

func (x StreamSubscriptionRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamSubscriptionRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_zenbpm_proto_enumTypes[1].Descriptor()
}

func (StreamSubscriptionRequest_Type) Type() protoreflect.EnumType {
	return &file_zenbpm_proto_enumTypes[1]
}

func (x StreamSubscriptionRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamSubscriptionRequest_Type.Descriptor instead.
func (StreamSubscriptionRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_zenbpm_proto_rawDescGZIP(), []int{1, 0}
}

type JobStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*JobStreamRequest_Subscription
	//	*JobStreamRequest_Complete
	//	*JobStreamRequest_Fail
	//	*JobStreamRequest_ExtendLock
	Request       isJobStreamRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStreamRequest) Reset() {
	*x = JobStreamRequest{}
	mi := &file_zenbpm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStreamRequest) ProtoMessage() {}

func (x *JobStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenbpm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStreamRequest.ProtoReflect.Descriptor instead.
func (*JobStreamRequest) Descriptor() ([]byte, []int) {
	return file_zenbpm_proto_rawDescGZIP(), []int{0}
}

func (x *JobStreamRequest) GetRequest() isJobStreamRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *JobStreamRequest) GetSubscription() *StreamSubscriptionRequest {
	if x != nil {
		if x, ok := x.Request.(*JobStreamRequest_Subscription); ok {
			return x.Subscription
		}
	}
	return nil
}

func (x *JobStreamRequest) GetComplete() *JobCompleteRequest {
	if x != nil {
		if x, ok := x.Request.(*JobStreamRequest_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *JobStreamRequest) GetFail() *JobFailRequest {
	if x != nil {
		if x, ok := x.Request.(*JobStreamRequest_Fail); ok {
			return x.Fail
		}
	}
	return nil
}

func (x *JobStreamRequest) GetExtendLock() *JobExtendLockRequest {
	if x != nil {
		if x, ok := x.Request.(*JobStreamRequest_ExtendLock); ok {
			return x.ExtendLock
		}
	}
	return nil
}

type isJobStreamRequest_Request interface {
	isJobStreamRequest_Request()
}

type JobStreamRequest_Subscription struct {
	Subscription *StreamSubscriptionRequest `protobuf:"bytes,1,opt,name=subscription,oneof"`
}

type JobStreamRequest_Complete struct {
	Complete *JobCompleteRequest `protobuf:"bytes,2,opt,name=complete,oneof"`
}

type JobStreamRequest_Fail struct {
	Fail *JobFailRequest `protobuf:"bytes,3,opt,name=fail,oneof"`
}

type JobStreamRequest_ExtendLock struct {
	ExtendLock *JobExtendLockRequest `protobuf:"bytes,4,opt,name=extend_lock,json=extendLock,oneof"`
}

func (*JobStreamRequest_Subscription) isJobStreamRequest_Request() {}

func (*JobStreamRequest_Complete) isJobStreamRequest_Request() {}

func (*JobStreamRequest_Fail) isJobStreamRequest_Request() {}

func (*JobStreamRequest_ExtendLock) isJobStreamRequest_Request() {}

type StreamSubscriptionRequest struct {
	state   protoimpl.MessageState          `protogen:"open.v1"`
	JobType *string                         `protobuf:"bytes,1,opt,name=job_type,json=jobType" json:"job_type,omitempty"`
	Type    *StreamSubscriptionRequest_Type `protobuf:"varint,2,opt,name=type,enum=grpc.StreamSubscriptionRequest_Type" json:"type,omitempty"`
	// How long a job of this type stays locked for this client after delivery, in milliseconds.
	// 0 = the engine's default (jobManager.defaultLockDurationMs). A value above
	// jobManager.maxLockDurationMs is capped, never rejected; the effective deadline is
	// reported in lock_until of every delivery.
	LockDurationMs *int64 `protobuf:"varint,3,opt,name=lock_duration_ms,json=lockDurationMs" json:"lock_duration_ms,omitempty"`
	// How many jobs of this type this client may hold at once. 0 = the engine's default
	// (jobManager.defaultMaxActiveJobs). A value above jobManager.maxActiveJobsCap is capped.
	MaxActiveJobs *int32 `protobuf:"varint,4,opt,name=max_active_jobs,json=maxActiveJobs" json:"max_active_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSubscriptionRequest) Reset() {
	*x = StreamSubscriptionRequest{}
	mi := &file_zenbpm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSubscriptionRequest) ProtoMessage() {}

func (x *StreamSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenbpm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*StreamSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_zenbpm_proto_rawDescGZIP(), []int{1}
}

func (x *StreamSubscriptionRequest) GetJobType() string {
	if x != nil && x.JobType != nil {
		return *x.JobType
	}
	return ""
}

func (x *StreamSubscriptionRequest) GetType() StreamSubscriptionRequest_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return StreamSubscriptionRequest_TYPE_UNDEFINED
}

func (x *StreamSubscriptionRequest) GetLockDurationMs() int64 {
	if x != nil && x.LockDurationMs != nil {
		return *x.LockDurationMs
	}
	return 0
}

func (x *StreamSubscriptionRequest) GetMaxActiveJobs() int32 {
	if x != nil && x.MaxActiveJobs != nil {
		return *x.MaxActiveJobs
	}
	return 0
}

type JobCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *int64                 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`            // job key
	Variables     []byte                 `protobuf:"bytes,2,opt,name=variables" json:"variables,omitempty"` // json variables
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobCompleteRequest) Reset() {
	*x = JobCompleteRequest{}
	mi := &file_zenbpm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCompleteRequest) ProtoMessage() {}

func (x *JobCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenbpm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCompleteRequest.ProtoReflect.Descriptor instead.
func (*JobCompleteRequest) Descriptor() ([]byte, []int) {
	return file_zenbpm_proto_rawDescGZIP(), []int{2}
}

func (x *JobCompleteRequest) GetKey() int64 {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return 0
}

func (x *JobCompleteRequest) GetVariables() []byte {
	if x != nil {
		return x.Variables
	}
	return nil
}

type JobFailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *int64                 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	ErrorCode     *string                `protobuf:"bytes,3,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	Variables     []byte                 `protobuf:"bytes,4,opt,name=variables" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFailRequest) Reset() {
	*x = JobFailRequest{}
	mi := &file_zenbpm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFailRequest) ProtoMessage() {}

func (x *JobFailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenbpm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFailRequest.ProtoReflect.Descriptor instead.
func (*JobFailRequest) Descriptor() ([]byte, []int) {
	return file_zenbpm_proto_rawDescGZIP(), []int{3}
}

func (x *JobFailRequest) GetKey() int64 {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return 0
}

func (x *JobFailRequest) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *JobFailRequest) GetErrorCode() string {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ""
}

func (x *JobFailRequest) GetVariables() []byte {
	if x != nil {
		return x.Variables
	}
	return nil
}

// Moves the lock deadline of a job this client holds to now plus lock_duration_ms.
// The engine answers with a LockExtended carrying the new deadline, or with an
// ErrorResult whose code is one of JobStreamErrorCode and a LockExtended carrying only the key.
type JobExtendLockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   *int64                 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	// 0 = extend by the lock_duration_ms of the subscription the job was delivered under.
	// A value above jobManager.maxLockDurationMs is capped.
	LockDurationMs *int64 `protobuf:"varint,2,opt,name=lock_duration_ms,json=lockDurationMs" json:"lock_duration_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobExtendLockRequest) Reset() {
	*x = JobExtendLockRequest{}
	mi := &file_zenbpm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobExtendLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobExtendLockRequest) ProtoMessage() {}

func (x *JobExtendLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenbpm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobExtendLockRequest.ProtoReflect.Descriptor instead.
func (*JobExtendLockRequest) Descriptor() ([]byte, []int) {
	return file_zenbpm_proto_rawDescGZIP(), []int{4}
}

func (x *JobExtendLockRequest) GetKey() int64 {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return 0
}

func (x *JobExtendLockRequest) GetLockDurationMs() int64 {
	if x != nil && x.LockDurationMs != nil {
		return *x.LockDurationMs
	}
	return 0
}

type JobStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error *ErrorResult           `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Job   *WaitingJob            `protobuf:"bytes,2,opt,name=job" json:"job,omitempty"`
	// The answer to a JobExtendLockRequest. On an error it carries only the key.
	LockExtended  *LockExtended `protobuf:"bytes,3,opt,name=lock_extended,json=lockExtended" json:"lock_extended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStreamResponse) Reset() {
	*x = JobStreamResponse{}
	mi := &file_zenbpm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStreamResponse) ProtoMessage() {}

func (x *JobStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zenbpm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStreamResponse.ProtoReflect.Descriptor instead.
func (*JobStreamResponse) Descriptor() ([]byte, []int) {
	return file_zenbpm_proto_rawDescGZIP(), []int{5}
}

func (x *JobStreamResponse) GetError() *ErrorResult {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *JobStreamResponse) GetJob() *WaitingJob {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *JobStreamResponse) GetLockExtended() *LockExtended {
	if x != nil {
		return x.LockExtended
	}
	return nil
}

type LockExtended struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   *int64                 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	// Unix milliseconds on the clock of the partition leader at which the lock lapses.
	LockUntil     *int64 `protobuf:"varint,2,opt,name=lock_until,json=lockUntil" json:"lock_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockExtended) Reset() {
	*x = LockExtended{}
	mi := &file_zenbpm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockExtended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockExtended) ProtoMessage() {}

func (x *LockExtended) ProtoReflect() protoreflect.Message {
	mi := &file_zenbpm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockExtended.ProtoReflect.Descriptor instead.
func (*LockExtended) Descriptor() ([]byte, []int) {
	return file_zenbpm_proto_rawDescGZIP(), []int{6}
}

func (x *LockExtended) GetKey() int64 {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return 0
}

func (x *LockExtended) GetLockUntil() int64 {
	if x != nil && x.LockUntil != nil {
		return *x.LockUntil
	}
	return 0
}

type WaitingJob struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            *int64                 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	InstanceKey    *int64                 `protobuf:"varint,2,opt,name=instance_key,json=instanceKey" json:"instance_key,omitempty"`
	InputVariables []byte                 `protobuf:"bytes,3,opt,name=input_variables,json=inputVariables" json:"input_variables,omitempty"`
	Type           *string                `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	ElementId      *string                `protobuf:"bytes,5,opt,name=element_id,json=elementId" json:"element_id,omitempty"`
	CreatedAt      *int64                 `protobuf:"varint,6,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	ElementType    *string                `protobuf:"bytes,7,opt,name=element_type,json=elementType" json:"element_type,omitempty"`
	// Unix milliseconds on the clock of the partition leader at which the lock this
	// delivery holds lapses. With synchronised clocks, lock_until minus the local time
	// estimates the remaining time; it is conservative, the leader counts the lock from
	// the end of the send. When the clocks cannot be trusted, count the lock duration
	// of the subscription from the moment of receipt instead of comparing timestamps.
	LockUntil     *int64 `protobuf:"varint,8,opt,name=lock_until,json=lockUntil" json:"lock_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitingJob) Reset() {
	*x = WaitingJob{}
	mi := &file_zenbpm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitingJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitingJob) ProtoMessage() {}

func (x *WaitingJob) ProtoReflect() protoreflect.Message {
	mi := &file_zenbpm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitingJob.ProtoReflect.Descriptor instead.
func (*WaitingJob) Descriptor() ([]byte, []int) {
	return file_zenbpm_proto_rawDescGZIP(), []int{7}
}

func (x *WaitingJob) GetKey() int64 {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return 0
}

func (x *WaitingJob) GetInstanceKey() int64 {
	if x != nil && x.InstanceKey != nil {
		return *x.InstanceKey
	}
	return 0
}

func (x *WaitingJob) GetInputVariables() []byte {
	if x != nil {
		return x.InputVariables
	}
	return nil
}

func (x *WaitingJob) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *WaitingJob) GetElementId() string {
	if x != nil && x.ElementId != nil {
		return *x.ElementId
	}
	return ""
}

func (x *WaitingJob) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *WaitingJob) GetElementType() string {
	if x != nil && x.ElementType != nil {
		return *x.ElementType
	}
	return ""
}

func (x *WaitingJob) GetLockUntil() int64 {
	if x != nil && x.LockUntil != nil {
		return *x.LockUntil
	}
	return 0
}

type ErrorResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *uint32                `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResult) Reset() {
	*x = ErrorResult{}
	mi := &file_zenbpm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResult) ProtoMessage() {}

func (x *ErrorResult) ProtoReflect() protoreflect.Message {
	mi := &file_zenbpm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResult.ProtoReflect.Descriptor instead.
func (*ErrorResult) Descriptor() ([]byte, []int) {
	return file_zenbpm_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorResult) GetCode() uint32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *ErrorResult) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_zenbpm_proto protoreflect.FileDescriptor

var file_zenbpm_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x7a, 0x65, 0x6e, 0x62, 0x70, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x67, 0x72, 0x70, 0x63, 0x22, 0x87, 0x02, 0x0a, 0x10, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x0c, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x36, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4a, 0x6f, 0x62, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08,
	0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x66, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4a, 0x6f,
	0x62, 0x46, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04,
	0x66, 0x61, 0x69, 0x6c, 0x12, 0x3d, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x5f, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x4a, 0x6f, 0x62, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x4c,
	0x6f, 0x63, 0x6b, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x88,
	0x02, 0x0a, 0x19, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x6a, 0x6f, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6a, 0x6f, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6c, 0x6f, 0x63,
	0x6b, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6d,
	0x61, 0x78, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6d, 0x61, 0x78, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4a,
	0x6f, 0x62, 0x73, 0x22, 0x44, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42,
	0x45, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x55,
	0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x02, 0x22, 0x44, 0x0a, 0x12, 0x4a, 0x6f, 0x62,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x22,
	0x79, 0x0a, 0x0e, 0x4a, 0x6f, 0x62, 0x46, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x14, 0x4a, 0x6f,
	0x62, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e,
	0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x22, 0x99,
	0x01, 0x0a, 0x11, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x22, 0x0a,
	0x03, 0x6a, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x4a, 0x6f, 0x62, 0x52, 0x03, 0x6a, 0x6f,
	0x62, 0x12, 0x37, 0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4c, 0x6f, 0x63, 0x6b, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x52, 0x0c, 0x6c, 0x6f,
	0x63, 0x6b, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x22, 0x3f, 0x0a, 0x0c, 0x4c, 0x6f,
	0x63, 0x6b, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x22, 0xfe, 0x01, 0x0a, 0x0a,
	0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x4a, 0x6f, 0x62, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x56,
	0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x22, 0x3b, 0x0a, 0x0b,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0xc7, 0x01, 0x0a, 0x12, 0x4a, 0x6f,
	0x62, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x25, 0x0a, 0x21, 0x4a, 0x4f, 0x42, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x27, 0x0a, 0x23, 0x4a, 0x4f, 0x42, 0x5f, 0x53,
	0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45,
	0x5f, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x48, 0x45, 0x4c, 0x44, 0x10, 0x01,
	0x12, 0x33, 0x0a, 0x2f, 0x4a, 0x4f, 0x42, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x48,
	0x45, 0x4c, 0x44, 0x5f, 0x42, 0x59, 0x5f, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x43, 0x4c, 0x49,
	0x45, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x2c, 0x0a, 0x28, 0x4a, 0x4f, 0x42, 0x5f, 0x53, 0x54, 0x52,
	0x45, 0x41, 0x4d, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4c,
	0x45, 0x41, 0x44, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c,
	0x45, 0x10, 0x03, 0x32, 0x4a, 0x0a, 0x06, 0x5a, 0x65, 0x6e, 0x42, 0x70, 0x6d, 0x12, 0x40, 0x0a,
	0x09, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x16, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x62,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x69, 0x76, 0x65, 0x2f, 0x7a, 0x65, 0x6e, 0x62, 0x70,
	0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70,
	0xe8, 0x07,
})

var (
	file_zenbpm_proto_rawDescOnce sync.Once
	file_zenbpm_proto_rawDescData []byte
)

func file_zenbpm_proto_rawDescGZIP() []byte {
	file_zenbpm_proto_rawDescOnce.Do(func() {
		file_zenbpm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zenbpm_proto_rawDesc), len(file_zenbpm_proto_rawDesc)))
	})
	return file_zenbpm_proto_rawDescData
}

var file_zenbpm_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_zenbpm_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_zenbpm_proto_goTypes = []any{
	(JobStreamErrorCode)(0),             // 0: grpc.JobStreamErrorCode
	(StreamSubscriptionRequest_Type)(0), // 1: grpc.StreamSubscriptionRequest.Type
	(*JobStreamRequest)(nil),            // 2: grpc.JobStreamRequest
	(*StreamSubscriptionRequest)(nil),   // 3: grpc.StreamSubscriptionRequest
	(*JobCompleteRequest)(nil),          // 4: grpc.JobCompleteRequest
	(*JobFailRequest)(nil),              // 5: grpc.JobFailRequest
	(*JobExtendLockRequest)(nil),        // 6: grpc.JobExtendLockRequest
	(*JobStreamResponse)(nil),           // 7: grpc.JobStreamResponse
	(*LockExtended)(nil),                // 8: grpc.LockExtended
	(*WaitingJob)(nil),                  // 9: grpc.WaitingJob
	(*ErrorResult)(nil),                 // 10: grpc.ErrorResult
}
var file_zenbpm_proto_depIdxs = []int32{
	3,  // 0: grpc.JobStreamRequest.subscription:type_name -> grpc.StreamSubscriptionRequest
	4,  // 1: grpc.JobStreamRequest.complete:type_name -> grpc.JobCompleteRequest
	5,  // 2: grpc.JobStreamRequest.fail:type_name -> grpc.JobFailRequest
	6,  // 3: grpc.JobStreamRequest.extend_lock:type_name -> grpc.JobExtendLockRequest
	1,  // 4: grpc.StreamSubscriptionRequest.type:type_name -> grpc.StreamSubscriptionRequest.Type
	10, // 5: grpc.JobStreamResponse.error:type_name -> grpc.ErrorResult
	9,  // 6: grpc.JobStreamResponse.job:type_name -> grpc.WaitingJob
	8,  // 7: grpc.JobStreamResponse.lock_extended:type_name -> grpc.LockExtended
	2,  // 8: grpc.ZenBpm.JobStream:input_type -> grpc.JobStreamRequest
	7,  // 9: grpc.ZenBpm.JobStream:output_type -> grpc.JobStreamResponse
	9,  // [9:10] is the sub-list for method output_type
	8,  // [8:9] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_zenbpm_proto_init() }
func file_zenbpm_proto_init() {
	if File_zenbpm_proto != nil {
		return
	}
	file_zenbpm_proto_msgTypes[0].OneofWrappers = []any{
		(*JobStreamRequest_Subscription)(nil),
		(*JobStreamRequest_Complete)(nil),
		(*JobStreamRequest_Fail)(nil),
		(*JobStreamRequest_ExtendLock)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zenbpm_proto_rawDesc), len(file_zenbpm_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zenbpm_proto_goTypes,
		DependencyIndexes: file_zenbpm_proto_depIdxs,
		EnumInfos:         file_zenbpm_proto_enumTypes,
		MessageInfos:      file_zenbpm_proto_msgTypes,
	}.Build()
	File_zenbpm_proto = out.File
	file_zenbpm_proto_goTypes = nil
	file_zenbpm_proto_depIdxs = nil
}
