// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: business_rule_execution.sql

package sql

import (
	"context"
)

const findBusinessRuleExecutionByKey = `-- name: FindBusinessRuleExecutionByKey :one
SELECT "key", decision_id, created_at, output_variables, evaluated_decisions
FROM business_rule_execution
WHERE key = ?1
`

func (q *Queries) FindBusinessRuleExecutionByKey(ctx context.Context, key int64) (BusinessRuleExecution, error) {
	row := q.db.QueryRowContext(ctx, findBusinessRuleExecutionByKey, key)
	var i BusinessRuleExecution
	err := row.Scan(
		&i.Key,
		&i.DecisionID,
		&i.CreatedAt,
		&i.OutputVariables,
		&i.EvaluatedDecisions,
	)
	return i, err
}

const saveBusinessRuleExecution = `-- name: SaveBusinessRuleExecution :exec
INSERT INTO business_rule_execution ( key,  decision_id, created_at, output_variables, evaluated_decisions)
VALUES (?, ?, ?, ?, ?)
`

type SaveBusinessRuleExecutionParams struct {
	Key                int64  `json:"key"`
	DecisionID         string `json:"decision_id"`
	CreatedAt          int64  `json:"created_at"`
	OutputVariables    string `json:"output_variables"`
	EvaluatedDecisions string `json:"evaluated_decisions"`
}

func (q *Queries) SaveBusinessRuleExecution(ctx context.Context, arg SaveBusinessRuleExecutionParams) error {
	_, err := q.db.ExecContext(ctx, saveBusinessRuleExecution,
		arg.Key,
		arg.DecisionID,
		arg.CreatedAt,
		arg.OutputVariables,
		arg.EvaluatedDecisions,
	)
	return err
}
