// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: decision_instance.sql

package sql

import (
	"context"
	"database/sql"
	"strings"
)

const deleteProcessInstancesDecisionInstances = `-- name: DeleteProcessInstancesDecisionInstances :exec
DELETE FROM decision_instance
WHERE process_instance_key IN (/*SLICE:keys*/?)
`

func (q *Queries) DeleteProcessInstancesDecisionInstances(ctx context.Context, keys []sql.NullInt64) error {
	query := deleteProcessInstancesDecisionInstances
	var queryParams []interface{}
	if len(keys) > 0 {
		for _, v := range keys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keys*/?", strings.Repeat(",?", len(keys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keys*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const findDecisionInstanceByKey = `-- name: FindDecisionInstanceByKey :one
SELECT "key", decision_id, created_at, output_variables, evaluated_decisions, dmn_resource_definition_key, decision_definition_key, process_instance_key, flow_element_instance_key
FROM decision_instance
WHERE key = ?1
`

func (q *Queries) FindDecisionInstanceByKey(ctx context.Context, key int64) (DecisionInstance, error) {
	row := q.db.QueryRowContext(ctx, findDecisionInstanceByKey, key)
	var i DecisionInstance
	err := row.Scan(
		&i.Key,
		&i.DecisionID,
		&i.CreatedAt,
		&i.OutputVariables,
		&i.EvaluatedDecisions,
		&i.DmnResourceDefinitionKey,
		&i.DecisionDefinitionKey,
		&i.ProcessInstanceKey,
		&i.FlowElementInstanceKey,
	)
	return i, err
}

const saveDecisionInstance = `-- name: SaveDecisionInstance :exec
INSERT INTO decision_instance (key, decision_id, created_at, output_variables, evaluated_decisions, dmn_resource_definition_key,
                               decision_definition_key, process_instance_key, flow_element_instance_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type SaveDecisionInstanceParams struct {
	Key                      int64         `json:"key"`
	DecisionID               string        `json:"decision_id"`
	CreatedAt                int64         `json:"created_at"`
	OutputVariables          string        `json:"output_variables"`
	EvaluatedDecisions       string        `json:"evaluated_decisions"`
	DmnResourceDefinitionKey int64         `json:"dmn_resource_definition_key"`
	DecisionDefinitionKey    int64         `json:"decision_definition_key"`
	ProcessInstanceKey       sql.NullInt64 `json:"process_instance_key"`
	FlowElementInstanceKey   sql.NullInt64 `json:"flow_element_instance_key"`
}

func (q *Queries) SaveDecisionInstance(ctx context.Context, arg SaveDecisionInstanceParams) error {
	_, err := q.db.ExecContext(ctx, saveDecisionInstance,
		arg.Key,
		arg.DecisionID,
		arg.CreatedAt,
		arg.OutputVariables,
		arg.EvaluatedDecisions,
		arg.DmnResourceDefinitionKey,
		arg.DecisionDefinitionKey,
		arg.ProcessInstanceKey,
		arg.FlowElementInstanceKey,
	)
	return err
}
