// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: decision.sql

package sql

import (
	"context"
)

const findDecisionByKey = `-- name: FindDecisionByKey :one
SELECT
    "key", version, decision_id, version_tag, decision_definition_id, decision_definition_key
FROM
    decision
WHERE
    key = ?1
`

func (q *Queries) FindDecisionByKey(ctx context.Context, key int64) (Decision, error) {
	row := q.db.QueryRowContext(ctx, findDecisionByKey, key)
	var i Decision
	err := row.Scan(
		&i.Key,
		&i.Version,
		&i.DecisionID,
		&i.VersionTag,
		&i.DecisionDefinitionID,
		&i.DecisionDefinitionKey,
	)
	return i, err
}

const findDecisionsById = `-- name: FindDecisionsById :many
SELECT
    "key", version, decision_id, version_tag, decision_definition_id, decision_definition_key
FROM
    decision
WHERE
    decision_id = ?1
ORDER BY
    version desc
`

func (q *Queries) FindDecisionsById(ctx context.Context, decisionID string) ([]Decision, error) {
	rows, err := q.db.QueryContext(ctx, findDecisionsById, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Decision{}
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.Key,
			&i.Version,
			&i.DecisionID,
			&i.VersionTag,
			&i.DecisionDefinitionID,
			&i.DecisionDefinitionKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLatestDecisionById = `-- name: FindLatestDecisionById :one
SELECT
    "key", version, decision_id, version_tag, decision_definition_id, decision_definition_key
FROM
    decision
WHERE
    decision_id = ?1
ORDER BY
    version DESC
LIMIT 1
`

func (q *Queries) FindLatestDecisionById(ctx context.Context, decisionID string) (Decision, error) {
	row := q.db.QueryRowContext(ctx, findLatestDecisionById, decisionID)
	var i Decision
	err := row.Scan(
		&i.Key,
		&i.Version,
		&i.DecisionID,
		&i.VersionTag,
		&i.DecisionDefinitionID,
		&i.DecisionDefinitionKey,
	)
	return i, err
}

const findLatestDecisionByIdAndDecisionDefinitionId = `-- name: FindLatestDecisionByIdAndDecisionDefinitionId :one
SELECT
    "key", version, decision_id, version_tag, decision_definition_id, decision_definition_key
FROM
    decision d
WHERE
    decision_id = ?1
    AND decision_definition_id = ?2
ORDER BY
    version DESC
LIMIT 1
`

type FindLatestDecisionByIdAndDecisionDefinitionIdParams struct {
	DecisionID           string `json:"decision_id"`
	DecisionDefinitionID string `json:"decision_definition_id"`
}

func (q *Queries) FindLatestDecisionByIdAndDecisionDefinitionId(ctx context.Context, arg FindLatestDecisionByIdAndDecisionDefinitionIdParams) (Decision, error) {
	row := q.db.QueryRowContext(ctx, findLatestDecisionByIdAndDecisionDefinitionId, arg.DecisionID, arg.DecisionDefinitionID)
	var i Decision
	err := row.Scan(
		&i.Key,
		&i.Version,
		&i.DecisionID,
		&i.VersionTag,
		&i.DecisionDefinitionID,
		&i.DecisionDefinitionKey,
	)
	return i, err
}

const findLatestDecisionByIdAndVersionTag = `-- name: FindLatestDecisionByIdAndVersionTag :one
SELECT
    "key", version, decision_id, version_tag, decision_definition_id, decision_definition_key
FROM
    decision
WHERE
    decision_id = ?1
    AND version_tag = ?2
ORDER BY
    version DESC
LIMIT 1
`

type FindLatestDecisionByIdAndVersionTagParams struct {
	DecisionID string `json:"decision_id"`
	VersionTag string `json:"version_tag"`
}

func (q *Queries) FindLatestDecisionByIdAndVersionTag(ctx context.Context, arg FindLatestDecisionByIdAndVersionTagParams) (Decision, error) {
	row := q.db.QueryRowContext(ctx, findLatestDecisionByIdAndVersionTag, arg.DecisionID, arg.VersionTag)
	var i Decision
	err := row.Scan(
		&i.Key,
		&i.Version,
		&i.DecisionID,
		&i.VersionTag,
		&i.DecisionDefinitionID,
		&i.DecisionDefinitionKey,
	)
	return i, err
}

const saveDecision = `-- name: SaveDecision :exec
INSERT INTO decision(key, version, decision_id, version_tag, decision_definition_id, decision_definition_key)
    VALUES (?, ?, ?, ?, ?, ?)
`

type SaveDecisionParams struct {
	Key                   int64  `json:"key"`
	Version               int64  `json:"version"`
	DecisionID            string `json:"decision_id"`
	VersionTag            string `json:"version_tag"`
	DecisionDefinitionID  string `json:"decision_definition_id"`
	DecisionDefinitionKey int64  `json:"decision_definition_key"`
}

func (q *Queries) SaveDecision(ctx context.Context, arg SaveDecisionParams) error {
	_, err := q.db.ExecContext(ctx, saveDecision,
		arg.Key,
		arg.Version,
		arg.DecisionID,
		arg.VersionTag,
		arg.DecisionDefinitionID,
		arg.DecisionDefinitionKey,
	)
	return err
}
