// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: decision_instance.sql

package sql

import (
	"context"
)

const findDecisionInstanceByKey = `-- name: FindDecisionInstanceByKey :one
SELECT "key", decision_id, created_at, output_variables, evaluated_decisions
FROM decision_instance
WHERE key = ?1
`

func (q *Queries) FindDecisionInstanceByKey(ctx context.Context, key int64) (DecisionInstance, error) {
	row := q.db.QueryRowContext(ctx, findDecisionInstanceByKey, key)
	var i DecisionInstance
	err := row.Scan(
		&i.Key,
		&i.DecisionID,
		&i.CreatedAt,
		&i.OutputVariables,
		&i.EvaluatedDecisions,
	)
	return i, err
}

const saveDecisionInstance = `-- name: SaveDecisionInstance :exec
INSERT INTO decision_instance ( key,  decision_id, created_at, output_variables, evaluated_decisions)
VALUES (?, ?, ?, ?, ?)
`

type SaveDecisionInstanceParams struct {
	Key                int64  `json:"key"`
	DecisionID         string `json:"decision_id"`
	CreatedAt          int64  `json:"created_at"`
	OutputVariables    string `json:"output_variables"`
	EvaluatedDecisions string `json:"evaluated_decisions"`
}

func (q *Queries) SaveDecisionInstance(ctx context.Context, arg SaveDecisionInstanceParams) error {
	_, err := q.db.ExecContext(ctx, saveDecisionInstance,
		arg.Key,
		arg.DecisionID,
		arg.CreatedAt,
		arg.OutputVariables,
		arg.EvaluatedDecisions,
	)
	return err
}
