// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: element_execution_counter.sql

package sql

import (
	"context"
	"strings"
)

const deleteElementExecutionCounters = `-- name: DeleteElementExecutionCounters :exec
DELETE FROM element_execution_counter
WHERE process_instance_key IN (/*SLICE:keys*/?)
`

func (q *Queries) DeleteElementExecutionCounters(ctx context.Context, keys []int64) error {
	query := deleteElementExecutionCounters
	var queryParams []interface{}
	if len(keys) > 0 {
		for _, v := range keys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keys*/?", strings.Repeat(",?", len(keys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keys*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getElementExecutionCount = `-- name: GetElementExecutionCount :one
SELECT
    execution_count
FROM
    element_execution_counter
WHERE
    process_instance_key = ?1
`

func (q *Queries) GetElementExecutionCount(ctx context.Context, processInstanceKey int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getElementExecutionCount, processInstanceKey)
	var execution_count int64
	err := row.Scan(&execution_count)
	return execution_count, err
}

const incrementElementExecutionCount = `-- name: IncrementElementExecutionCount :exec
INSERT INTO element_execution_counter (process_instance_key, execution_count)
    VALUES (?1, 1)
ON CONFLICT (process_instance_key)
    DO UPDATE SET
        execution_count = execution_count + 1
`

func (q *Queries) IncrementElementExecutionCount(ctx context.Context, processInstanceKey int64) error {
	_, err := q.db.ExecContext(ctx, incrementElementExecutionCount, processInstanceKey)
	return err
}

const resetProcessInstanceExecutionCount = `-- name: ResetProcessInstanceExecutionCount :exec
UPDATE element_execution_counter
SET execution_count = 0
WHERE process_instance_key = ?1
`

func (q *Queries) ResetProcessInstanceExecutionCount(ctx context.Context, processInstanceKey int64) error {
	_, err := q.db.ExecContext(ctx, resetProcessInstanceExecutionCount, processInstanceKey)
	return err
}
