// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: flow_element_instance.sql

package sql

import (
	"context"
	"strings"
)

const deleteFlowElementInstance = `-- name: DeleteFlowElementInstance :exec
DELETE FROM flow_element_instance
WHERE process_instance_key IN (/*SLICE:keys*/?)
`

func (q *Queries) DeleteFlowElementInstance(ctx context.Context, keys []int64) error {
	query := deleteFlowElementInstance
	var queryParams []interface{}
	if len(keys) > 0 {
		for _, v := range keys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keys*/?", strings.Repeat(",?", len(keys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keys*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getFlowElementInstance = `-- name: GetFlowElementInstance :many
SELECT
    "key", element_id, process_instance_key, execution_token_key, created_at, input_variables, output_variables
FROM
    flow_element_instance
WHERE
    process_instance_key = ?1
`

func (q *Queries) GetFlowElementInstance(ctx context.Context, processInstanceKey int64) ([]FlowElementInstance, error) {
	rows, err := q.db.QueryContext(ctx, getFlowElementInstance, processInstanceKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowElementInstance{}
	for rows.Next() {
		var i FlowElementInstance
		if err := rows.Scan(
			&i.Key,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.ExecutionTokenKey,
			&i.CreatedAt,
			&i.InputVariables,
			&i.OutputVariables,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowElementInstanceByTokenKey = `-- name: GetFlowElementInstanceByTokenKey :many
SELECT
    "key", element_id, process_instance_key, execution_token_key, created_at, input_variables, output_variables
FROM
    flow_element_instance
WHERE
    execution_token_key = ?1
ORDER BY created_at DESC
`

func (q *Queries) GetFlowElementInstanceByTokenKey(ctx context.Context, executionTokenKey int64) ([]FlowElementInstance, error) {
	rows, err := q.db.QueryContext(ctx, getFlowElementInstanceByTokenKey, executionTokenKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowElementInstance{}
	for rows.Next() {
		var i FlowElementInstance
		if err := rows.Scan(
			&i.Key,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.ExecutionTokenKey,
			&i.CreatedAt,
			&i.InputVariables,
			&i.OutputVariables,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveFlowElementInstance = `-- name: SaveFlowElementInstance :exec
INSERT INTO flow_element_instance(key, element_id, process_instance_key, created_at, execution_token_key, input_variables, output_variables)
    VALUES (?, ? ,? ,?, ?, ?, ?)
ON CONFLICT
    DO UPDATE SET
       output_variables = excluded.output_variables
`

type SaveFlowElementInstanceParams struct {
	Key                int64  `json:"key"`
	ElementID          string `json:"element_id"`
	ProcessInstanceKey int64  `json:"process_instance_key"`
	CreatedAt          int64  `json:"created_at"`
	ExecutionTokenKey  int64  `json:"execution_token_key"`
	InputVariables     string `json:"input_variables"`
	OutputVariables    string `json:"output_variables"`
}

func (q *Queries) SaveFlowElementInstance(ctx context.Context, arg SaveFlowElementInstanceParams) error {
	_, err := q.db.ExecContext(ctx, saveFlowElementInstance,
		arg.Key,
		arg.ElementID,
		arg.ProcessInstanceKey,
		arg.CreatedAt,
		arg.ExecutionTokenKey,
		arg.InputVariables,
		arg.OutputVariables,
	)
	return err
}
