// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: flow_element_history.sql

package sql

import (
	"context"
	"strings"
)

const deleteFlowElementHistory = `-- name: DeleteFlowElementHistory :exec
DELETE FROM flow_element_history
WHERE process_instance_key IN (/*SLICE:keys*/?)
`

func (q *Queries) DeleteFlowElementHistory(ctx context.Context, keys []int64) error {
	query := deleteFlowElementHistory
	var queryParams []interface{}
	if len(keys) > 0 {
		for _, v := range keys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keys*/?", strings.Repeat(",?", len(keys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keys*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getFlowElementHistory = `-- name: GetFlowElementHistory :many
SELECT
    "key", element_id, process_instance_key, created_at,
    COUNT(*) OVER() AS total_count
FROM
    flow_element_history
WHERE
    process_instance_key = ?1
LIMIT ?3 OFFSET ?2
`

type GetFlowElementHistoryParams struct {
	ProcessInstanceKey int64 `json:"process_instance_key"`
	Offset             int64 `json:"offset"`
	Limit              int64 `json:"limit"`
}

type GetFlowElementHistoryRow struct {
	Key                int64  `json:"key"`
	ElementID          string `json:"element_id"`
	ProcessInstanceKey int64  `json:"process_instance_key"`
	CreatedAt          int64  `json:"created_at"`
	TotalCount         int64  `json:"total_count"`
}

func (q *Queries) GetFlowElementHistory(ctx context.Context, arg GetFlowElementHistoryParams) ([]GetFlowElementHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getFlowElementHistory, arg.ProcessInstanceKey, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFlowElementHistoryRow{}
	for rows.Next() {
		var i GetFlowElementHistoryRow
		if err := rows.Scan(
			&i.Key,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveFlowElementHistory = `-- name: SaveFlowElementHistory :exec
INSERT INTO flow_element_history(key, element_id, process_instance_key, created_at)
    VALUES (?, ? ,? ,?)
ON CONFLICT
    DO UPDATE SET
       process_instance_key = excluded.process_instance_key,
       element_id = excluded.element_id
`

type SaveFlowElementHistoryParams struct {
	Key                int64  `json:"key"`
	ElementID          string `json:"element_id"`
	ProcessInstanceKey int64  `json:"process_instance_key"`
	CreatedAt          int64  `json:"created_at"`
}

func (q *Queries) SaveFlowElementHistory(ctx context.Context, arg SaveFlowElementHistoryParams) error {
	_, err := q.db.ExecContext(ctx, saveFlowElementHistory,
		arg.Key,
		arg.ElementID,
		arg.ProcessInstanceKey,
		arg.CreatedAt,
	)
	return err
}
