// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: job.sql

package sql

import (
	"context"
	"database/sql"
	"strings"
)

const countWaitingJobs = `-- name: CountWaitingJobs :one
SELECT
    count(*)
FROM
    job
WHERE
    state = 1
`

func (q *Queries) CountWaitingJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWaitingJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProcessInstancesJobs = `-- name: DeleteProcessInstancesJobs :exec
DELETE FROM job
WHERE process_instance_key IN (/*SLICE:keys*/?)
`

func (q *Queries) DeleteProcessInstancesJobs(ctx context.Context, keys []int64) error {
	query := deleteProcessInstancesJobs
	var queryParams []interface{}
	if len(keys) > 0 {
		for _, v := range keys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keys*/?", strings.Repeat(",?", len(keys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keys*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const findActiveJobsByType = `-- name: FindActiveJobsByType :many
SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, input_variables, execution_token, assignee, output_variables, element_type, retries, attempts, retry_at, last_failure_message, retry_backoff, retries_set_by_operator, delivery_token, failed_delivery_token
FROM
    job
WHERE
    type = ?1
    AND state = 1
    AND (retry_at IS NULL OR retry_at <= CAST(?2 AS INTEGER))
`

type FindActiveJobsByTypeParams struct {
	Type string `json:"type"`
	Now  int64  `json:"now"`
}

func (q *Queries) FindActiveJobsByType(ctx context.Context, arg FindActiveJobsByTypeParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, findActiveJobsByType, arg.Type, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.Key,
			&i.ElementInstanceKey,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.Type,
			&i.State,
			&i.CreatedAt,
			&i.InputVariables,
			&i.ExecutionToken,
			&i.Assignee,
			&i.OutputVariables,
			&i.ElementType,
			&i.Retries,
			&i.Attempts,
			&i.RetryAt,
			&i.LastFailureMessage,
			&i.RetryBackoff,
			&i.RetriesSetByOperator,
			&i.DeliveryToken,
			&i.FailedDeliveryToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllJobs = `-- name: FindAllJobs :many
SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, input_variables, execution_token, assignee, output_variables, element_type, retries, attempts, retry_at, last_failure_message, retry_backoff, retries_set_by_operator, delivery_token, failed_delivery_token
FROM
    job
LIMIT ?2 offset ?1
`

type FindAllJobsParams struct {
	Offset int64 `json:"offset"`
	Size   int64 `json:"size"`
}

func (q *Queries) FindAllJobs(ctx context.Context, arg FindAllJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, findAllJobs, arg.Offset, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.Key,
			&i.ElementInstanceKey,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.Type,
			&i.State,
			&i.CreatedAt,
			&i.InputVariables,
			&i.ExecutionToken,
			&i.Assignee,
			&i.OutputVariables,
			&i.ElementType,
			&i.Retries,
			&i.Attempts,
			&i.RetryAt,
			&i.LastFailureMessage,
			&i.RetryBackoff,
			&i.RetriesSetByOperator,
			&i.DeliveryToken,
			&i.FailedDeliveryToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findJobByJobKey = `-- name: FindJobByJobKey :one
SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, input_variables, execution_token, assignee, output_variables, element_type, retries, attempts, retry_at, last_failure_message, retry_backoff, retries_set_by_operator, delivery_token, failed_delivery_token
FROM
    job
WHERE
    key = ?1
`

func (q *Queries) FindJobByJobKey(ctx context.Context, key int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, findJobByJobKey, key)
	var i Job
	err := row.Scan(
		&i.Key,
		&i.ElementInstanceKey,
		&i.ElementID,
		&i.ProcessInstanceKey,
		&i.Type,
		&i.State,
		&i.CreatedAt,
		&i.InputVariables,
		&i.ExecutionToken,
		&i.Assignee,
		&i.OutputVariables,
		&i.ElementType,
		&i.Retries,
		&i.Attempts,
		&i.RetryAt,
		&i.LastFailureMessage,
		&i.RetryBackoff,
		&i.RetriesSetByOperator,
		&i.DeliveryToken,
		&i.FailedDeliveryToken,
	)
	return i, err
}

const findJobByKey = `-- name: FindJobByKey :one
SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, input_variables, execution_token, assignee, output_variables, element_type, retries, attempts, retry_at, last_failure_message, retry_backoff, retries_set_by_operator, delivery_token, failed_delivery_token
FROM
    job
WHERE
    key = ?1
`

func (q *Queries) FindJobByKey(ctx context.Context, key int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, findJobByKey, key)
	var i Job
	err := row.Scan(
		&i.Key,
		&i.ElementInstanceKey,
		&i.ElementID,
		&i.ProcessInstanceKey,
		&i.Type,
		&i.State,
		&i.CreatedAt,
		&i.InputVariables,
		&i.ExecutionToken,
		&i.Assignee,
		&i.OutputVariables,
		&i.ElementType,
		&i.Retries,
		&i.Attempts,
		&i.RetryAt,
		&i.LastFailureMessage,
		&i.RetryBackoff,
		&i.RetriesSetByOperator,
		&i.DeliveryToken,
		&i.FailedDeliveryToken,
	)
	return i, err
}

const findJobs = `-- name: FindJobs :many
SELECT
  j."key", j.element_instance_key, j.element_id, j.process_instance_key, j.type, j.state, j.created_at, j.input_variables, j.execution_token, j.assignee, j.output_variables, j.element_type, j.retries, j.attempts, j.retry_at, j.last_failure_message, j.retry_backoff, j.retries_set_by_operator, j.delivery_token, j.failed_delivery_token,
  COUNT(*) OVER() AS total_count
FROM job AS j
WHERE
  CAST(?1 AS TEXT) IS CAST(?1 AS TEXT)
  AND COALESCE(?2, type) = type
  AND COALESCE(?3, state) = state
  AND (CAST(?4 AS INTEGER) IS NULL OR j.process_instance_key = CAST(?4 AS TEXT)) 
  AND (CAST(?5 AS TEXT) IS NULL OR j.assignee = CAST(?5 AS TEXT)) 
  
ORDER BY
  CASE CAST(?1 AS TEXT) WHEN 'created_at_asc'  THEN j.created_at END ASC,
  CASE CAST(?1 AS TEXT) WHEN 'created_at_desc' THEN j.created_at END DESC,
  CASE CAST(?1 AS TEXT) WHEN 'key_asc' THEN j."key" END ASC,
  CASE CAST(?1 AS TEXT) WHEN 'key_desc' THEN j."key" END DESC,
  CASE CAST(?1 AS TEXT) WHEN 'type_asc' THEN j."type" END ASC,
  CASE CAST(?1 AS TEXT) WHEN 'type_desc' THEN j."type" END DESC,
  CASE CAST(?1 AS TEXT) WHEN 'state_asc' THEN j.state END ASC,
  CASE CAST(?1 AS TEXT) WHEN 'state_desc' THEN j.state END DESC,
  j."key" DESC

LIMIT ?7
OFFSET ?6
`

type FindJobsParams struct {
	Sort               sql.NullString `json:"sort"`
	Type               sql.NullString `json:"type"`
	State              sql.NullInt64  `json:"state"`
	ProcessInstanceKey sql.NullInt64  `json:"process_instance_key"`
	Assignee           sql.NullString `json:"assignee"`
	Offset             int64          `json:"offset"`
	Limit              int64          `json:"limit"`
}

type FindJobsRow struct {
	Job        Job   `json:"job"`
	TotalCount int64 `json:"total_count"`
}

// force sqlc to keep sort param
// workaround for sqlc does not replace params in order by
func (q *Queries) FindJobs(ctx context.Context, arg FindJobsParams) ([]FindJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, findJobs,
		arg.Sort,
		arg.Type,
		arg.State,
		arg.ProcessInstanceKey,
		arg.Assignee,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindJobsRow{}
	for rows.Next() {
		var i FindJobsRow
		if err := rows.Scan(
			&i.Job.Key,
			&i.Job.ElementInstanceKey,
			&i.Job.ElementID,
			&i.Job.ProcessInstanceKey,
			&i.Job.Type,
			&i.Job.State,
			&i.Job.CreatedAt,
			&i.Job.InputVariables,
			&i.Job.ExecutionToken,
			&i.Job.Assignee,
			&i.Job.OutputVariables,
			&i.Job.ElementType,
			&i.Job.Retries,
			&i.Job.Attempts,
			&i.Job.RetryAt,
			&i.Job.LastFailureMessage,
			&i.Job.RetryBackoff,
			&i.Job.RetriesSetByOperator,
			&i.Job.DeliveryToken,
			&i.Job.FailedDeliveryToken,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProcessInstanceJobs = `-- name: FindProcessInstanceJobs :many
SELECT
    job."key", job.element_instance_key, job.element_id, job.process_instance_key, job.type, job.state, job.created_at, job.input_variables, job.execution_token, job.assignee, job.output_variables, job.element_type, job.retries, job.attempts, job.retry_at, job.last_failure_message, job.retry_backoff, job.retries_set_by_operator, job.delivery_token, job.failed_delivery_token,
    COUNT(*) OVER () AS total_count
FROM
    job
WHERE
    process_instance_key = ?1
LIMIT ?3 OFFSET ?2
`

type FindProcessInstanceJobsParams struct {
	ProcessInstanceKey int64 `json:"process_instance_key"`
	Offset             int64 `json:"offset"`
	Size               int64 `json:"size"`
}

type FindProcessInstanceJobsRow struct {
	Job        Job   `json:"job"`
	TotalCount int64 `json:"total_count"`
}

func (q *Queries) FindProcessInstanceJobs(ctx context.Context, arg FindProcessInstanceJobsParams) ([]FindProcessInstanceJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, findProcessInstanceJobs, arg.ProcessInstanceKey, arg.Offset, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindProcessInstanceJobsRow{}
	for rows.Next() {
		var i FindProcessInstanceJobsRow
		if err := rows.Scan(
			&i.Job.Key,
			&i.Job.ElementInstanceKey,
			&i.Job.ElementID,
			&i.Job.ProcessInstanceKey,
			&i.Job.Type,
			&i.Job.State,
			&i.Job.CreatedAt,
			&i.Job.InputVariables,
			&i.Job.ExecutionToken,
			&i.Job.Assignee,
			&i.Job.OutputVariables,
			&i.Job.ElementType,
			&i.Job.Retries,
			&i.Job.Attempts,
			&i.Job.RetryAt,
			&i.Job.LastFailureMessage,
			&i.Job.RetryBackoff,
			&i.Job.RetriesSetByOperator,
			&i.Job.DeliveryToken,
			&i.Job.FailedDeliveryToken,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProcessInstanceJobsInState = `-- name: FindProcessInstanceJobsInState :many
SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, input_variables, execution_token, assignee, output_variables, element_type, retries, attempts, retry_at, last_failure_message, retry_backoff, retries_set_by_operator, delivery_token, failed_delivery_token
FROM
    job INDEXED BY idx_fk_job_process_instance_key
WHERE
    process_instance_key = ?1
    AND state IN (/*SLICE:states*/?)
`

type FindProcessInstanceJobsInStateParams struct {
	ProcessInstanceKey int64   `json:"process_instance_key"`
	States             []int64 `json:"states"`
}

// Pinned to idx_fk_job_process_instance_key. The planner currently picks it correctly, but
// pinning here makes the contract explicit and prevents the generic idx_job_execution_token_state
// from shadowing it under different data distributions. See TestHotPathIndexes.
func (q *Queries) FindProcessInstanceJobsInState(ctx context.Context, arg FindProcessInstanceJobsInStateParams) ([]Job, error) {
	query := findProcessInstanceJobsInState
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProcessInstanceKey)
	if len(arg.States) > 0 {
		for _, v := range arg.States {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:states*/?", strings.Repeat(",?", len(arg.States))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:states*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.Key,
			&i.ElementInstanceKey,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.Type,
			&i.State,
			&i.CreatedAt,
			&i.InputVariables,
			&i.ExecutionToken,
			&i.Assignee,
			&i.OutputVariables,
			&i.ElementType,
			&i.Retries,
			&i.Attempts,
			&i.RetryAt,
			&i.LastFailureMessage,
			&i.RetryBackoff,
			&i.RetriesSetByOperator,
			&i.DeliveryToken,
			&i.FailedDeliveryToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsInStateByTokenKey = `-- name: GetJobsInStateByTokenKey :many

SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, input_variables, execution_token, assignee, output_variables, element_type, retries, attempts, retry_at, last_failure_message, retry_backoff, retries_set_by_operator, delivery_token, failed_delivery_token
FROM
    job
WHERE
    execution_token = ?1
    AND state IN (/*SLICE:states*/?)
`

type GetJobsInStateByTokenKeyParams struct {
	ExecutionTokenKey int64   `json:"execution_token_key"`
	States            []int64 `json:"states"`
}

// https://github.com/sqlc-dev/sqlc/issues/2452
func (q *Queries) GetJobsInStateByTokenKey(ctx context.Context, arg GetJobsInStateByTokenKeyParams) ([]Job, error) {
	query := getJobsInStateByTokenKey
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ExecutionTokenKey)
	if len(arg.States) > 0 {
		for _, v := range arg.States {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:states*/?", strings.Repeat(",?", len(arg.States))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:states*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.Key,
			&i.ElementInstanceKey,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.Type,
			&i.State,
			&i.CreatedAt,
			&i.InputVariables,
			&i.ExecutionToken,
			&i.Assignee,
			&i.OutputVariables,
			&i.ElementType,
			&i.Retries,
			&i.Attempts,
			&i.RetryAt,
			&i.LastFailureMessage,
			&i.RetryBackoff,
			&i.RetriesSetByOperator,
			&i.DeliveryToken,
			&i.FailedDeliveryToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWaitingJobs = `-- name: GetWaitingJobs :many
SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, input_variables, execution_token, assignee, output_variables, element_type, retries, attempts, retry_at, last_failure_message, retry_backoff, retries_set_by_operator, delivery_token, failed_delivery_token
FROM
    job
WHERE
    state = 1
    AND type IN (/*SLICE:type*/?)
    AND key NOT IN (/*SLICE:key_skip*/?)
    AND (retry_at IS NULL OR retry_at <= CAST(? AS INTEGER))
ORDER BY
    created_at ASC
LIMIT ?
`

type GetWaitingJobsParams struct {
	Type    []string `json:"type"`
	KeySkip []int64  `json:"key_skip"`
	Now     int64    `json:"now"`
	Limit   int64    `json:"limit"`
}

func (q *Queries) GetWaitingJobs(ctx context.Context, arg GetWaitingJobsParams) ([]Job, error) {
	query := getWaitingJobs
	var queryParams []interface{}
	if len(arg.Type) > 0 {
		for _, v := range arg.Type {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:type*/?", strings.Repeat(",?", len(arg.Type))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:type*/?", "NULL", 1)
	}
	if len(arg.KeySkip) > 0 {
		for _, v := range arg.KeySkip {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:key_skip*/?", strings.Repeat(",?", len(arg.KeySkip))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:key_skip*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Now)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.Key,
			&i.ElementInstanceKey,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.Type,
			&i.State,
			&i.CreatedAt,
			&i.InputVariables,
			&i.ExecutionToken,
			&i.Assignee,
			&i.OutputVariables,
			&i.ElementType,
			&i.Retries,
			&i.Attempts,
			&i.RetryAt,
			&i.LastFailureMessage,
			&i.RetryBackoff,
			&i.RetriesSetByOperator,
			&i.DeliveryToken,
			&i.FailedDeliveryToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordJobDelivery = `-- name: RecordJobDelivery :execrows
UPDATE job
SET delivery_token = ?1
WHERE key = ?2
    AND state = 1
    AND delivery_token = ?3
`

type RecordJobDeliveryParams struct {
	DeliveryToken       int64 `json:"delivery_token"`
	Key                 int64 `json:"key"`
	LoadedDeliveryToken int64 `json:"loaded_delivery_token"`
}

// Raises the delivery token of a job the job manager hands out, provided it still waits for a worker
// and no other delivery was recorded since it was loaded. No row affected = do not hand it out.
func (q *Queries) RecordJobDelivery(ctx context.Context, arg RecordJobDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordJobDelivery, arg.DeliveryToken, arg.Key, arg.LoadedDeliveryToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveJob = `-- name: SaveJob :exec
INSERT INTO job(key, element_id, element_type, element_instance_key, process_instance_key, type, state, created_at, input_variables, output_variables, execution_token, assignee, retries, attempts, retry_at, last_failure_message, retry_backoff, retries_set_by_operator, delivery_token, failed_delivery_token)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT
    DO UPDATE SET
        state = excluded.state,
        input_variables = excluded.input_variables,
        output_variables = excluded.output_variables,
        assignee = excluded.assignee,
        retries = excluded.retries,
        attempts = excluded.attempts,
        retry_at = excluded.retry_at,
        last_failure_message = excluded.last_failure_message,
        retries_set_by_operator = excluded.retries_set_by_operator,
        failed_delivery_token = excluded.failed_delivery_token
`

type SaveJobParams struct {
	Key                  int64          `json:"key"`
	ElementID            string         `json:"element_id"`
	ElementType          string         `json:"element_type"`
	ElementInstanceKey   int64          `json:"element_instance_key"`
	ProcessInstanceKey   int64          `json:"process_instance_key"`
	Type                 string         `json:"type"`
	State                int64          `json:"state"`
	CreatedAt            int64          `json:"created_at"`
	InputVariables       string         `json:"input_variables"`
	OutputVariables      sql.NullString `json:"output_variables"`
	ExecutionToken       int64          `json:"execution_token"`
	Assignee             sql.NullString `json:"assignee"`
	Retries              int64          `json:"retries"`
	Attempts             int64          `json:"attempts"`
	RetryAt              sql.NullInt64  `json:"retry_at"`
	LastFailureMessage   sql.NullString `json:"last_failure_message"`
	RetryBackoff         sql.NullString `json:"retry_backoff"`
	RetriesSetByOperator int64          `json:"retries_set_by_operator"`
	DeliveryToken        int64          `json:"delivery_token"`
	FailedDeliveryToken  int64          `json:"failed_delivery_token"`
}

// retry_backoff is left out of the update on purpose: the policy is fixed when the job is created.
// delivery_token is left out as well: only RecordJobDelivery writes it, so that a job the engine read
// before a delivery was recorded does not take the token back when it is saved.
func (q *Queries) SaveJob(ctx context.Context, arg SaveJobParams) error {
	_, err := q.db.ExecContext(ctx, saveJob,
		arg.Key,
		arg.ElementID,
		arg.ElementType,
		arg.ElementInstanceKey,
		arg.ProcessInstanceKey,
		arg.Type,
		arg.State,
		arg.CreatedAt,
		arg.InputVariables,
		arg.OutputVariables,
		arg.ExecutionToken,
		arg.Assignee,
		arg.Retries,
		arg.Attempts,
		arg.RetryAt,
		arg.LastFailureMessage,
		arg.RetryBackoff,
		arg.RetriesSetByOperator,
		arg.DeliveryToken,
		arg.FailedDeliveryToken,
	)
	return err
}

const withdrawJobDelivery = `-- name: WithdrawJobDelivery :execrows
UPDATE job
SET delivery_token = ?1
WHERE key = ?2
    AND delivery_token = ?3
`

type WithdrawJobDeliveryParams struct {
	PreviousDeliveryToken int64 `json:"previous_delivery_token"`
	Key                   int64 `json:"key"`
	DeliveryToken         int64 `json:"delivery_token"`
}

// Takes back the token of a delivery the job manager recorded but never sent, so that the delivery
// before it counts again. Only while no other delivery was recorded since; the token was never handed
// out, so issuing it again later is harmless.
func (q *Queries) WithdrawJobDelivery(ctx context.Context, arg WithdrawJobDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, withdrawJobDelivery, arg.PreviousDeliveryToken, arg.Key, arg.DeliveryToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
