// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"database/sql"
)

type Decision struct {
	Version               int64  `json:"version"`
	DecisionID            string `json:"decision_id"`
	VersionTag            string `json:"version_tag"`
	DecisionDefinitionID  string `json:"decision_definition_id"`
	DecisionDefinitionKey int64  `json:"decision_definition_key"`
}

type DecisionDefinition struct {
	Key             int64  `json:"key"`
	Version         int64  `json:"version"`
	DmnID           string `json:"dmn_id"`
	DmnData         string `json:"dmn_data"`
	DmnChecksum     []byte `json:"dmn_checksum"`
	DmnResourceName string `json:"dmn_resource_name"`
}

type ExecutionToken struct {
	Key                int64  `json:"key"`
	ElementInstanceKey int64  `json:"element_instance_key"`
	ElementID          string `json:"element_id"`
	ProcessInstanceKey int64  `json:"process_instance_key"`
	State              int64  `json:"state"`
	CreatedAt          int64  `json:"created_at"`
}

type FlowElementHistory struct {
	Key                int64  `json:"key"`
	ElementID          string `json:"element_id"`
	ProcessInstanceKey int64  `json:"process_instance_key"`
	CreatedAt          int64  `json:"created_at"`
}

type Incident struct {
	Key                int64         `json:"key"`
	ElementInstanceKey int64         `json:"element_instance_key"`
	ElementID          string        `json:"element_id"`
	ProcessInstanceKey int64         `json:"process_instance_key"`
	Message            string        `json:"message"`
	CreatedAt          int64         `json:"created_at"`
	ResolvedAt         sql.NullInt64 `json:"resolved_at"`
	ExecutionToken     int64         `json:"execution_token"`
}

type Job struct {
	Key                int64  `json:"key"`
	ElementInstanceKey int64  `json:"element_instance_key"`
	ElementID          string `json:"element_id"`
	ProcessInstanceKey int64  `json:"process_instance_key"`
	Type               string `json:"type"`
	State              int64  `json:"state"`
	CreatedAt          int64  `json:"created_at"`
	Variables          string `json:"variables"`
	ExecutionToken     int64  `json:"execution_token"`
}

type MessageSubscription struct {
	Key                  int64  `json:"key"`
	ElementID            string `json:"element_id"`
	ProcessDefinitionKey int64  `json:"process_definition_key"`
	ProcessInstanceKey   int64  `json:"process_instance_key"`
	Name                 string `json:"name"`
	State                int64  `json:"state"`
	CreatedAt            int64  `json:"created_at"`
	CorrelationKey       string `json:"correlation_key"`
	ExecutionToken       int64  `json:"execution_token"`
}

type MessageSubscriptionPointer struct {
	Name                   string `json:"name"`
	CorrelationKey         string `json:"correlation_key"`
	State                  int64  `json:"state"`
	CreatedAt              int64  `json:"created_at"`
	MessageSubscriptionKey int64  `json:"message_subscription_key"`
	ExecutionTokenKey      int64  `json:"execution_token_key"`
}

type Migration struct {
	Name  string `json:"name"`
	RanAt int64  `json:"ran_at"`
}

type ProcessDefinition struct {
	Key              int64  `json:"key"`
	Version          int64  `json:"version"`
	BpmnProcessID    string `json:"bpmn_process_id"`
	BpmnData         string `json:"bpmn_data"`
	BpmnChecksum     []byte `json:"bpmn_checksum"`
	BpmnResourceName string `json:"bpmn_resource_name"`
}

type ProcessInstance struct {
	Key                         int64          `json:"key"`
	ProcessDefinitionKey        int64          `json:"process_definition_key"`
	BusinessKey                 sql.NullString `json:"business_key"`
	CreatedAt                   int64          `json:"created_at"`
	State                       int64          `json:"state"`
	Variables                   string         `json:"variables"`
	ParentProcessExecutionToken sql.NullInt64  `json:"parent_process_execution_token"`
	HistoryTtlSec               sql.NullInt64  `json:"history_ttl_sec"`
	HistoryDeleteSec            sql.NullInt64  `json:"history_delete_sec"`
}

type Timer struct {
	Key                  int64  `json:"key"`
	ElementInstanceKey   int64  `json:"element_instance_key"`
	ElementID            string `json:"element_id"`
	ProcessDefinitionKey int64  `json:"process_definition_key"`
	ProcessInstanceKey   int64  `json:"process_instance_key"`
	State                int64  `json:"state"`
	CreatedAt            int64  `json:"created_at"`
	DueAt                int64  `json:"due_at"`
	ExecutionToken       int64  `json:"execution_token"`
}
