// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sql

import (
	"context"
)

type Querier interface {
	FindActiveJobsByType(ctx context.Context, type_ string) ([]Job, error)
	FindAllJobs(ctx context.Context, arg FindAllJobsParams) ([]Job, error)
	FindElementTimers(ctx context.Context, arg FindElementTimersParams) ([]Timer, error)
	FindJobByElementId(ctx context.Context, arg FindJobByElementIdParams) (Job, error)
	FindJobByJobKey(ctx context.Context, key int64) (Job, error)
	FindJobByKey(ctx context.Context, key int64) (Job, error)
	FindJobsWithStates(ctx context.Context, arg FindJobsWithStatesParams) ([]Job, error)
	FindLatestProcessDefinitionById(ctx context.Context, bpmnProcessID string) (ProcessDefinition, error)
	FindMessageSubscriptions(ctx context.Context, arg FindMessageSubscriptionsParams) ([]MessageSubscription, error)
	FindProcessDefinitionByKey(ctx context.Context, key int64) (ProcessDefinition, error)
	FindProcessDefinitions(ctx context.Context, arg FindProcessDefinitionsParams) ([]ProcessDefinition, error)
	FindProcessDefinitionsByIds(ctx context.Context, bpmnProcessIds string) ([]ProcessDefinition, error)
	FindProcessInstanceJobsInState(ctx context.Context, arg FindProcessInstanceJobsInStateParams) ([]Job, error)
	FindProcessInstanceMessageSubscriptions(ctx context.Context, arg FindProcessInstanceMessageSubscriptionsParams) ([]MessageSubscription, error)
	FindProcessInstances(ctx context.Context, arg FindProcessInstancesParams) ([]ProcessInstance, error)
	FindTimers(ctx context.Context, arg FindTimersParams) ([]Timer, error)
	FindTimersInState(ctx context.Context, arg FindTimersInStateParams) ([]Timer, error)
	FindTokenMessageSubscriptions(ctx context.Context, arg FindTokenMessageSubscriptionsParams) ([]MessageSubscription, error)
	GetProcessInstance(ctx context.Context, key int64) (ProcessInstance, error)
	GetTokens(ctx context.Context, keys []int64) ([]ExecutionToken, error)
	GetTokensForProcessInstance(ctx context.Context, arg GetTokensForProcessInstanceParams) ([]ExecutionToken, error)
	GetTokensInStateForPartition(ctx context.Context, arg GetTokensInStateForPartitionParams) ([]ExecutionToken, error)
	SaveJob(ctx context.Context, arg SaveJobParams) error
	SaveMessageSubscription(ctx context.Context, arg SaveMessageSubscriptionParams) error
	SaveProcessDefinition(ctx context.Context, arg SaveProcessDefinitionParams) error
	SaveProcessInstance(ctx context.Context, arg SaveProcessInstanceParams) error
	SaveTimer(ctx context.Context, arg SaveTimerParams) error
	SaveToken(ctx context.Context, arg SaveTokenParams) error
}

var _ Querier = (*Queries)(nil)
