// Code generated by "stringer -type=TimerState"; DO NOT EDIT.

package runtime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TimerStateCreated-1]
	_ = x[TimerStateTriggered-2]
	_ = x[TimerStateCancelled-3]
}

const _TimerState_name = "TimerStateCreatedTimerStateTriggeredTimerStateCancelled"

var _TimerState_index = [...]uint8{0, 17, 36, 55}

func (i TimerState) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_TimerState_index)-1 {
		return "TimerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimerState_name[_TimerState_index[idx]:_TimerState_index[idx+1]]
}
