// Code generated by "stringer -type=TokenState"; DO NOT EDIT.

package runtime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenStateRunning-1]
	_ = x[TokenStateWaiting-2]
	_ = x[TokenStateCompleted-3]
	_ = x[TokenStateCanceled-4]
	_ = x[TokenStateFailed-5]
}

const _TokenState_name = "TokenStateRunningTokenStateWaitingTokenStateCompletedTokenStateCanceledTokenStateFailed"

var _TokenState_index = [...]uint8{0, 17, 34, 53, 71, 87}

func (i TokenState) String() string {
	i -= 1
	if i < 0 || i >= TokenState(len(_TokenState_index)-1) {
		return "TokenState(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenState_name[_TokenState_index[i]:_TokenState_index[i+1]]
}
