// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.1
// source: zen_cluster.proto

package proto

import (
	proto "github.com/pbinitiative/zenbpm/internal/cluster/command/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TODO: do we want to keep custom error struct or use the default error handling?
type ErrorResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResult) Reset() {
	*x = ErrorResult{}
	mi := &file_zen_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResult) ProtoMessage() {}

func (x *ErrorResult) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResult.ProtoReflect.Descriptor instead.
func (*ErrorResult) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResult) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_zen_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotifyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorResult           `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_zen_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyResponse) GetError() *ErrorResult {
	if x != nil {
		return x.Error
	}
	return nil
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Voter         bool                   `protobuf:"varint,3,opt,name=voter,proto3" json:"voter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_zen_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoinRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *JoinRequest) GetVoter() bool {
	if x != nil {
		return x.Voter
	}
	return false
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorResult           `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Leader        string                 `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_zen_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *JoinResponse) GetError() *ErrorResult {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *JoinResponse) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

type AddPartitionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Voter         bool                   `protobuf:"varint,3,opt,name=voter,proto3" json:"voter,omitempty"`
	Partition     uint32                 `protobuf:"varint,4,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPartitionNodeRequest) Reset() {
	*x = AddPartitionNodeRequest{}
	mi := &file_zen_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPartitionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPartitionNodeRequest) ProtoMessage() {}

func (x *AddPartitionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPartitionNodeRequest.ProtoReflect.Descriptor instead.
func (*AddPartitionNodeRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *AddPartitionNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddPartitionNodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddPartitionNodeRequest) GetVoter() bool {
	if x != nil {
		return x.Voter
	}
	return false
}

func (x *AddPartitionNodeRequest) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type AddPartitionNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorResult           `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPartitionNodeResponse) Reset() {
	*x = AddPartitionNodeResponse{}
	mi := &file_zen_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPartitionNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPartitionNodeResponse) ProtoMessage() {}

func (x *AddPartitionNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPartitionNodeResponse.ProtoReflect.Descriptor instead.
func (*AddPartitionNodeResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *AddPartitionNodeResponse) GetError() *ErrorResult {
	if x != nil {
		return x.Error
	}
	return nil
}

type ShutdownPartitionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Partition     uint32                 `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownPartitionNodeRequest) Reset() {
	*x = ShutdownPartitionNodeRequest{}
	mi := &file_zen_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownPartitionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownPartitionNodeRequest) ProtoMessage() {}

func (x *ShutdownPartitionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownPartitionNodeRequest.ProtoReflect.Descriptor instead.
func (*ShutdownPartitionNodeRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *ShutdownPartitionNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShutdownPartitionNodeRequest) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type ShutdownPartitionNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorResult           `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownPartitionNodeResponse) Reset() {
	*x = ShutdownPartitionNodeResponse{}
	mi := &file_zen_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownPartitionNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownPartitionNodeResponse) ProtoMessage() {}

func (x *ShutdownPartitionNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownPartitionNodeResponse.ProtoReflect.Descriptor instead.
func (*ShutdownPartitionNodeResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *ShutdownPartitionNodeResponse) GetError() *ErrorResult {
	if x != nil {
		return x.Error
	}
	return nil
}

type PartitionNodeLeaderChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Partition     uint32                 `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionNodeLeaderChangeRequest) Reset() {
	*x = PartitionNodeLeaderChangeRequest{}
	mi := &file_zen_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionNodeLeaderChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionNodeLeaderChangeRequest) ProtoMessage() {}

func (x *PartitionNodeLeaderChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionNodeLeaderChangeRequest.ProtoReflect.Descriptor instead.
func (*PartitionNodeLeaderChangeRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *PartitionNodeLeaderChangeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PartitionNodeLeaderChangeRequest) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type PartitionNodeLeaderChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorResult           `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionNodeLeaderChangeResponse) Reset() {
	*x = PartitionNodeLeaderChangeResponse{}
	mi := &file_zen_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionNodeLeaderChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionNodeLeaderChangeResponse) ProtoMessage() {}

func (x *PartitionNodeLeaderChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionNodeLeaderChangeResponse.ProtoReflect.Descriptor instead.
func (*PartitionNodeLeaderChangeResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *PartitionNodeLeaderChangeResponse) GetError() *ErrorResult {
	if x != nil {
		return x.Error
	}
	return nil
}

type RemovePartitionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Partition     uint32                 `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePartitionNodeRequest) Reset() {
	*x = RemovePartitionNodeRequest{}
	mi := &file_zen_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePartitionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePartitionNodeRequest) ProtoMessage() {}

func (x *RemovePartitionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePartitionNodeRequest.ProtoReflect.Descriptor instead.
func (*RemovePartitionNodeRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *RemovePartitionNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemovePartitionNodeRequest) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type RemovePartitionNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorResult           `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePartitionNodeResponse) Reset() {
	*x = RemovePartitionNodeResponse{}
	mi := &file_zen_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePartitionNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePartitionNodeResponse) ProtoMessage() {}

func (x *RemovePartitionNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePartitionNodeResponse.ProtoReflect.Descriptor instead.
func (*RemovePartitionNodeResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *RemovePartitionNodeResponse) GetError() *ErrorResult {
	if x != nil {
		return x.Error
	}
	return nil
}

type ResumePartitionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Partition     uint32                 `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumePartitionNodeRequest) Reset() {
	*x = ResumePartitionNodeRequest{}
	mi := &file_zen_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumePartitionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumePartitionNodeRequest) ProtoMessage() {}

func (x *ResumePartitionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumePartitionNodeRequest.ProtoReflect.Descriptor instead.
func (*ResumePartitionNodeRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *ResumePartitionNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResumePartitionNodeRequest) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type ResumePartitionNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorResult           `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumePartitionNodeResponse) Reset() {
	*x = ResumePartitionNodeResponse{}
	mi := &file_zen_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumePartitionNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumePartitionNodeResponse) ProtoMessage() {}

func (x *ResumePartitionNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumePartitionNodeResponse.ProtoReflect.Descriptor instead.
func (*ResumePartitionNodeResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *ResumePartitionNodeResponse) GetError() *ErrorResult {
	if x != nil {
		return x.Error
	}
	return nil
}

// TODO: implement missing messages when needed by cluster communication
type PartitionRestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionRestoreRequest) Reset() {
	*x = PartitionRestoreRequest{}
	mi := &file_zen_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionRestoreRequest) ProtoMessage() {}

func (x *PartitionRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionRestoreRequest.ProtoReflect.Descriptor instead.
func (*PartitionRestoreRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{15}
}

type PartitionRestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionRestoreResponse) Reset() {
	*x = PartitionRestoreResponse{}
	mi := &file_zen_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionRestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionRestoreResponse) ProtoMessage() {}

func (x *PartitionRestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionRestoreResponse.ProtoReflect.Descriptor instead.
func (*PartitionRestoreResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{16}
}

type PartitionBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionBackupRequest) Reset() {
	*x = PartitionBackupRequest{}
	mi := &file_zen_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionBackupRequest) ProtoMessage() {}

func (x *PartitionBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionBackupRequest.ProtoReflect.Descriptor instead.
func (*PartitionBackupRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{17}
}

type PartitionBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionBackupResponse) Reset() {
	*x = PartitionBackupResponse{}
	mi := &file_zen_cluster_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionBackupResponse) ProtoMessage() {}

func (x *PartitionBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionBackupResponse.ProtoReflect.Descriptor instead.
func (*PartitionBackupResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{18}
}

type UnassignPartitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignPartitionRequest) Reset() {
	*x = UnassignPartitionRequest{}
	mi := &file_zen_cluster_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignPartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignPartitionRequest) ProtoMessage() {}

func (x *UnassignPartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignPartitionRequest.ProtoReflect.Descriptor instead.
func (*UnassignPartitionRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{19}
}

type UnassignPartitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignPartitionResponse) Reset() {
	*x = UnassignPartitionResponse{}
	mi := &file_zen_cluster_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignPartitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignPartitionResponse) ProtoMessage() {}

func (x *UnassignPartitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignPartitionResponse.ProtoReflect.Descriptor instead.
func (*UnassignPartitionResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{20}
}

type AssignPartitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPartitionRequest) Reset() {
	*x = AssignPartitionRequest{}
	mi := &file_zen_cluster_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPartitionRequest) ProtoMessage() {}

func (x *AssignPartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPartitionRequest.ProtoReflect.Descriptor instead.
func (*AssignPartitionRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{21}
}

type AssignPartitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPartitionResponse) Reset() {
	*x = AssignPartitionResponse{}
	mi := &file_zen_cluster_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPartitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPartitionResponse) ProtoMessage() {}

func (x *AssignPartitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPartitionResponse.ProtoReflect.Descriptor instead.
func (*AssignPartitionResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{22}
}

type ConfigurationUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationUpdateRequest) Reset() {
	*x = ConfigurationUpdateRequest{}
	mi := &file_zen_cluster_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationUpdateRequest) ProtoMessage() {}

func (x *ConfigurationUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationUpdateRequest.ProtoReflect.Descriptor instead.
func (*ConfigurationUpdateRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{23}
}

type ConfigurationUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationUpdateResponse) Reset() {
	*x = ConfigurationUpdateResponse{}
	mi := &file_zen_cluster_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationUpdateResponse) ProtoMessage() {}

func (x *ConfigurationUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationUpdateResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationUpdateResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{24}
}

type ClusterRestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterRestoreRequest) Reset() {
	*x = ClusterRestoreRequest{}
	mi := &file_zen_cluster_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRestoreRequest) ProtoMessage() {}

func (x *ClusterRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRestoreRequest.ProtoReflect.Descriptor instead.
func (*ClusterRestoreRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{25}
}

type ClusterRestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterRestoreResponse) Reset() {
	*x = ClusterRestoreResponse{}
	mi := &file_zen_cluster_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterRestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRestoreResponse) ProtoMessage() {}

func (x *ClusterRestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRestoreResponse.ProtoReflect.Descriptor instead.
func (*ClusterRestoreResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{26}
}

type ClusterBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterBackupRequest) Reset() {
	*x = ClusterBackupRequest{}
	mi := &file_zen_cluster_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterBackupRequest) ProtoMessage() {}

func (x *ClusterBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterBackupRequest.ProtoReflect.Descriptor instead.
func (*ClusterBackupRequest) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{27}
}

type ClusterBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterBackupResponse) Reset() {
	*x = ClusterBackupResponse{}
	mi := &file_zen_cluster_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterBackupResponse) ProtoMessage() {}

func (x *ClusterBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterBackupResponse.ProtoReflect.Descriptor instead.
func (*ClusterBackupResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{28}
}

type NodeCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error *ErrorResult           `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Type  proto.Command_Type     `protobuf:"varint,2,opt,name=type,proto3,enum=zencommand.Command_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*NodeCommandResponse_NodeChange
	//	*NodeCommandResponse_NodePartitionChange
	Response      isNodeCommandResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCommandResponse) Reset() {
	*x = NodeCommandResponse{}
	mi := &file_zen_cluster_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCommandResponse) ProtoMessage() {}

func (x *NodeCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCommandResponse.ProtoReflect.Descriptor instead.
func (*NodeCommandResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{29}
}

func (x *NodeCommandResponse) GetError() *ErrorResult {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *NodeCommandResponse) GetType() proto.Command_Type {
	if x != nil {
		return x.Type
	}
	return proto.Command_Type(0)
}

func (x *NodeCommandResponse) GetResponse() isNodeCommandResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *NodeCommandResponse) GetNodeChange() *ClusterNodeChangeResponse {
	if x != nil {
		if x, ok := x.Response.(*NodeCommandResponse_NodeChange); ok {
			return x.NodeChange
		}
	}
	return nil
}

func (x *NodeCommandResponse) GetNodePartitionChange() *ClusterNodePartitionChangeResponse {
	if x != nil {
		if x, ok := x.Response.(*NodeCommandResponse_NodePartitionChange); ok {
			return x.NodePartitionChange
		}
	}
	return nil
}

type isNodeCommandResponse_Response interface {
	isNodeCommandResponse_Response()
}

type NodeCommandResponse_NodeChange struct {
	NodeChange *ClusterNodeChangeResponse `protobuf:"bytes,3,opt,name=node_change,json=nodeChange,proto3,oneof"`
}

type NodeCommandResponse_NodePartitionChange struct {
	NodePartitionChange *ClusterNodePartitionChangeResponse `protobuf:"bytes,4,opt,name=node_partition_change,json=nodePartitionChange,proto3,oneof"`
}

func (*NodeCommandResponse_NodeChange) isNodeCommandResponse_Response() {}

func (*NodeCommandResponse_NodePartitionChange) isNodeCommandResponse_Response() {}

type ClusterNodeChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterNodeChangeResponse) Reset() {
	*x = ClusterNodeChangeResponse{}
	mi := &file_zen_cluster_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterNodeChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterNodeChangeResponse) ProtoMessage() {}

func (x *ClusterNodeChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterNodeChangeResponse.ProtoReflect.Descriptor instead.
func (*ClusterNodeChangeResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{30}
}

type ClusterNodePartitionChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterNodePartitionChangeResponse) Reset() {
	*x = ClusterNodePartitionChangeResponse{}
	mi := &file_zen_cluster_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterNodePartitionChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterNodePartitionChangeResponse) ProtoMessage() {}

func (x *ClusterNodePartitionChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zen_cluster_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterNodePartitionChangeResponse.ProtoReflect.Descriptor instead.
func (*ClusterNodePartitionChangeResponse) Descriptor() ([]byte, []int) {
	return file_zen_cluster_proto_rawDescGZIP(), []int{31}
}

var File_zen_cluster_proto protoreflect.FileDescriptor

var file_zen_cluster_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x7a, 0x65, 0x6e, 0x5f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x1a, 0x10, 0x7a, 0x65,
	0x6e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b,
	0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x39, 0x0a, 0x0d, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x4b, 0x0a, 0x0e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x4d, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x6f, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x6f, 0x74,
	0x65, 0x72, 0x22, 0x61, 0x0a, 0x0c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x77, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x6f,
	0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x55,
	0x0a, 0x18, 0x41, 0x64, 0x64, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4c, 0x0a, 0x1c, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77,
	0x6e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x5a, 0x0a, 0x1d, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x50, 0x0a, 0x20, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65,
	0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x5e, 0x0a, 0x21, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f,
	0x64, 0x65, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x4a, 0x0a, 0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x58, 0x0a,
	0x1b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4a, 0x0a, 0x1a, 0x52, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x58, 0x0a, 0x1b, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x19, 0x0a,
	0x17, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19,
	0x0a, 0x17, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x63, 0x6b, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x55, 0x6e, 0x61,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x55, 0x6e, 0x61, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a,
	0x16, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x17, 0x0a, 0x15, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xb4, 0x02, 0x0a, 0x13, 0x4e, 0x6f, 0x64,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x01, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01,
	0x01, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x7a, 0x65, 0x6e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x45, 0x0a, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x6e, 0x6f, 0x64, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x61, 0x0a, 0x15, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x70,
	0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x00, 0x52, 0x13, 0x6e, 0x6f, 0x64, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x1b, 0x0a, 0x19, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x0a, 0x22,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x9d, 0x0a, 0x0a, 0x0a, 0x5a, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x39, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x16, 0x2e, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x04,
	0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x14, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4a,
	0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x57, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x41, 0x64, 0x64, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x15, 0x53, 0x68,
	0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x25, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x68,
	0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x72, 0x0a, 0x19, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x6f, 0x64, 0x65, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x29, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f,
	0x64, 0x65, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x2e,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x23, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x1d, 0x2e, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x42, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x1e, 0x2e, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a,
	0x13, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x54, 0x0a, 0x0f, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x11, 0x55, 0x6e, 0x61, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x54, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x12, 0x1f, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x10, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x20, 0x2e, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x40, 0x0a, 0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x13, 0x2e, 0x7a, 0x65, 0x6e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x1c, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x62, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x69, 0x76, 0x65, 0x2f, 0x7a, 0x65,
	0x6e, 0x62, 0x70, 0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_zen_cluster_proto_rawDescOnce sync.Once
	file_zen_cluster_proto_rawDescData []byte
)

func file_zen_cluster_proto_rawDescGZIP() []byte {
	file_zen_cluster_proto_rawDescOnce.Do(func() {
		file_zen_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zen_cluster_proto_rawDesc), len(file_zen_cluster_proto_rawDesc)))
	})
	return file_zen_cluster_proto_rawDescData
}

var file_zen_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_zen_cluster_proto_goTypes = []any{
	(*ErrorResult)(nil),                        // 0: cluster.ErrorResult
	(*NotifyRequest)(nil),                      // 1: cluster.NotifyRequest
	(*NotifyResponse)(nil),                     // 2: cluster.NotifyResponse
	(*JoinRequest)(nil),                        // 3: cluster.JoinRequest
	(*JoinResponse)(nil),                       // 4: cluster.JoinResponse
	(*AddPartitionNodeRequest)(nil),            // 5: cluster.AddPartitionNodeRequest
	(*AddPartitionNodeResponse)(nil),           // 6: cluster.AddPartitionNodeResponse
	(*ShutdownPartitionNodeRequest)(nil),       // 7: cluster.ShutdownPartitionNodeRequest
	(*ShutdownPartitionNodeResponse)(nil),      // 8: cluster.ShutdownPartitionNodeResponse
	(*PartitionNodeLeaderChangeRequest)(nil),   // 9: cluster.PartitionNodeLeaderChangeRequest
	(*PartitionNodeLeaderChangeResponse)(nil),  // 10: cluster.PartitionNodeLeaderChangeResponse
	(*RemovePartitionNodeRequest)(nil),         // 11: cluster.RemovePartitionNodeRequest
	(*RemovePartitionNodeResponse)(nil),        // 12: cluster.RemovePartitionNodeResponse
	(*ResumePartitionNodeRequest)(nil),         // 13: cluster.ResumePartitionNodeRequest
	(*ResumePartitionNodeResponse)(nil),        // 14: cluster.ResumePartitionNodeResponse
	(*PartitionRestoreRequest)(nil),            // 15: cluster.PartitionRestoreRequest
	(*PartitionRestoreResponse)(nil),           // 16: cluster.PartitionRestoreResponse
	(*PartitionBackupRequest)(nil),             // 17: cluster.PartitionBackupRequest
	(*PartitionBackupResponse)(nil),            // 18: cluster.PartitionBackupResponse
	(*UnassignPartitionRequest)(nil),           // 19: cluster.UnassignPartitionRequest
	(*UnassignPartitionResponse)(nil),          // 20: cluster.UnassignPartitionResponse
	(*AssignPartitionRequest)(nil),             // 21: cluster.AssignPartitionRequest
	(*AssignPartitionResponse)(nil),            // 22: cluster.AssignPartitionResponse
	(*ConfigurationUpdateRequest)(nil),         // 23: cluster.ConfigurationUpdateRequest
	(*ConfigurationUpdateResponse)(nil),        // 24: cluster.ConfigurationUpdateResponse
	(*ClusterRestoreRequest)(nil),              // 25: cluster.ClusterRestoreRequest
	(*ClusterRestoreResponse)(nil),             // 26: cluster.ClusterRestoreResponse
	(*ClusterBackupRequest)(nil),               // 27: cluster.ClusterBackupRequest
	(*ClusterBackupResponse)(nil),              // 28: cluster.ClusterBackupResponse
	(*NodeCommandResponse)(nil),                // 29: cluster.NodeCommandResponse
	(*ClusterNodeChangeResponse)(nil),          // 30: cluster.ClusterNodeChangeResponse
	(*ClusterNodePartitionChangeResponse)(nil), // 31: cluster.ClusterNodePartitionChangeResponse
	(proto.Command_Type)(0),                    // 32: zencommand.Command.Type
	(*proto.Command)(nil),                      // 33: zencommand.Command
}
var file_zen_cluster_proto_depIdxs = []int32{
	0,  // 0: cluster.NotifyResponse.error:type_name -> cluster.ErrorResult
	0,  // 1: cluster.JoinResponse.error:type_name -> cluster.ErrorResult
	0,  // 2: cluster.AddPartitionNodeResponse.error:type_name -> cluster.ErrorResult
	0,  // 3: cluster.ShutdownPartitionNodeResponse.error:type_name -> cluster.ErrorResult
	0,  // 4: cluster.PartitionNodeLeaderChangeResponse.error:type_name -> cluster.ErrorResult
	0,  // 5: cluster.RemovePartitionNodeResponse.error:type_name -> cluster.ErrorResult
	0,  // 6: cluster.ResumePartitionNodeResponse.error:type_name -> cluster.ErrorResult
	0,  // 7: cluster.NodeCommandResponse.error:type_name -> cluster.ErrorResult
	32, // 8: cluster.NodeCommandResponse.type:type_name -> zencommand.Command.Type
	30, // 9: cluster.NodeCommandResponse.node_change:type_name -> cluster.ClusterNodeChangeResponse
	31, // 10: cluster.NodeCommandResponse.node_partition_change:type_name -> cluster.ClusterNodePartitionChangeResponse
	1,  // 11: cluster.ZenService.Notify:input_type -> cluster.NotifyRequest
	3,  // 12: cluster.ZenService.Join:input_type -> cluster.JoinRequest
	5,  // 13: cluster.ZenService.AddPartitionNode:input_type -> cluster.AddPartitionNodeRequest
	7,  // 14: cluster.ZenService.ShutdownPartitionNode:input_type -> cluster.ShutdownPartitionNodeRequest
	9,  // 15: cluster.ZenService.PartitionNodeLeaderChange:input_type -> cluster.PartitionNodeLeaderChangeRequest
	11, // 16: cluster.ZenService.RemovePartitionNode:input_type -> cluster.RemovePartitionNodeRequest
	13, // 17: cluster.ZenService.ResumePartitionNode:input_type -> cluster.ResumePartitionNodeRequest
	27, // 18: cluster.ZenService.ClusterBackup:input_type -> cluster.ClusterBackupRequest
	25, // 19: cluster.ZenService.ClusterRestore:input_type -> cluster.ClusterRestoreRequest
	23, // 20: cluster.ZenService.ConfigurationUpdate:input_type -> cluster.ConfigurationUpdateRequest
	21, // 21: cluster.ZenService.AssignPartition:input_type -> cluster.AssignPartitionRequest
	19, // 22: cluster.ZenService.UnassignPartition:input_type -> cluster.UnassignPartitionRequest
	17, // 23: cluster.ZenService.PartitionBackup:input_type -> cluster.PartitionBackupRequest
	15, // 24: cluster.ZenService.PartitionRestore:input_type -> cluster.PartitionRestoreRequest
	33, // 25: cluster.ZenService.NodeCommand:input_type -> zencommand.Command
	2,  // 26: cluster.ZenService.Notify:output_type -> cluster.NotifyResponse
	4,  // 27: cluster.ZenService.Join:output_type -> cluster.JoinResponse
	6,  // 28: cluster.ZenService.AddPartitionNode:output_type -> cluster.AddPartitionNodeResponse
	8,  // 29: cluster.ZenService.ShutdownPartitionNode:output_type -> cluster.ShutdownPartitionNodeResponse
	10, // 30: cluster.ZenService.PartitionNodeLeaderChange:output_type -> cluster.PartitionNodeLeaderChangeResponse
	12, // 31: cluster.ZenService.RemovePartitionNode:output_type -> cluster.RemovePartitionNodeResponse
	14, // 32: cluster.ZenService.ResumePartitionNode:output_type -> cluster.ResumePartitionNodeResponse
	28, // 33: cluster.ZenService.ClusterBackup:output_type -> cluster.ClusterBackupResponse
	26, // 34: cluster.ZenService.ClusterRestore:output_type -> cluster.ClusterRestoreResponse
	24, // 35: cluster.ZenService.ConfigurationUpdate:output_type -> cluster.ConfigurationUpdateResponse
	22, // 36: cluster.ZenService.AssignPartition:output_type -> cluster.AssignPartitionResponse
	20, // 37: cluster.ZenService.UnassignPartition:output_type -> cluster.UnassignPartitionResponse
	18, // 38: cluster.ZenService.PartitionBackup:output_type -> cluster.PartitionBackupResponse
	16, // 39: cluster.ZenService.PartitionRestore:output_type -> cluster.PartitionRestoreResponse
	29, // 40: cluster.ZenService.NodeCommand:output_type -> cluster.NodeCommandResponse
	26, // [26:41] is the sub-list for method output_type
	11, // [11:26] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_zen_cluster_proto_init() }
func file_zen_cluster_proto_init() {
	if File_zen_cluster_proto != nil {
		return
	}
	file_zen_cluster_proto_msgTypes[2].OneofWrappers = []any{}
	file_zen_cluster_proto_msgTypes[4].OneofWrappers = []any{}
	file_zen_cluster_proto_msgTypes[6].OneofWrappers = []any{}
	file_zen_cluster_proto_msgTypes[8].OneofWrappers = []any{}
	file_zen_cluster_proto_msgTypes[10].OneofWrappers = []any{}
	file_zen_cluster_proto_msgTypes[12].OneofWrappers = []any{}
	file_zen_cluster_proto_msgTypes[14].OneofWrappers = []any{}
	file_zen_cluster_proto_msgTypes[29].OneofWrappers = []any{
		(*NodeCommandResponse_NodeChange)(nil),
		(*NodeCommandResponse_NodePartitionChange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zen_cluster_proto_rawDesc), len(file_zen_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zen_cluster_proto_goTypes,
		DependencyIndexes: file_zen_cluster_proto_depIdxs,
		MessageInfos:      file_zen_cluster_proto_msgTypes,
	}.Build()
	File_zen_cluster_proto = out.File
	file_zen_cluster_proto_goTypes = nil
	file_zen_cluster_proto_depIdxs = nil
}
