// Code generated by "stringer -type=NodeState"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeStateError-1]
	_ = x[NodeStateStarted-2]
	_ = x[NodeStateShutdown-3]
}

const _NodeState_name = "NodeStateErrorNodeStateStartedNodeStateShutdown"

var _NodeState_index = [...]uint8{0, 14, 30, 47}

func (i NodeState) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_NodeState_index)-1 {
		return "NodeState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeState_name[_NodeState_index[idx]:_NodeState_index[idx+1]]
}
