name: go test
on: [ push, pull_request ]
jobs:
  go-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.24']
    name: Go ${{ matrix.go }} test
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: go test
        run: go test ./...
