name: go-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.24']
    name: Go ${{ matrix.go }} test
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Setup Golang caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: download modules
        run: go mod download
      - name: show pwd
        run: echo $(pwd)
      - name: make localbin dir
        run: mkdir bin
      - name: export localbin to path
        run: export PATH="$PATH:$(pwd)/bin"
      - name: path
        run: echo $PATH
      - name: run generate
        run: make generate
      - name: tests
        run: make test
