name: license-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Checking license header
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: license-check-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21" # or "stable"
          cache: true

      - name: Ensure script is executable
        run: chmod +x scripts/license-headers.sh || true # adjust if you use a different filename

      - name: License header check
        run: make license.check
