name: release

on:
  push:
    tags:
      - v*

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  release:
    uses: ./.github/workflows/release-reusable.yaml
    with:
      release-command: make release
      release-tag: ${{ github.ref_name }}
      artifact-prefix: trivy-release-reports
      publish: true
      security-scan: true
      notify: true
    secrets: inherit
