name: release

on:
  push:
    tags:
      - v*

permissions:
  actions: read
  contents: write
  pull-requests: write
  security-events: write

jobs:
  release:
    uses: ./.github/workflows/release-orchestrator.yaml
    with:
      version: ${{ github.ref_name }}
      backend_tag_exists: true
    secrets: inherit
