{
 "title": "ZenBPM",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Process instaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(bpmn_process_id) (rate(processes_started_total[$__interval]))",
     "legendFormat": "started-{{bpmn_process_id}}"
    },
    {
     "expr": "sum by(bpmn_process_id) (rate(processes_completed_total[$__interval]))",
     "legendFormat": "completed-{{bpmn_process_id}}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(type) (rate(jobs_created_total[$__interval]))",
     "legendFormat": "created-{{type}}"
    },
    {
     "expr": "sum by(type) (rate(jobs_completed_total[$__interval]))",
     "legendFormat": "completed-{{type}}"
    },
    {
     "expr": "sum(rate(jobs_completed_total[$__interval]))",
     "legendFormat": "total completed"
    },
    {
     "expr": "sum(rate(jobs_created_total[$__interval]))",
     "legendFormat": "total created"
    }
   ]
  },
  {
   "title": "Job distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(client) (rate(jobs_distributed_total[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(jobs_distributed_total[$__interval]))",
     "legendFormat": "total distributed"
    }
   ]
  },
  {
   "title": "Waiting jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "jobs_waiting", "legendFormat": "partition-{{partition}}" }
   ]
  },
  {
   "title": "Processes running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "processes_running", "legendFormat": "{{bpmn_process_id}}" }
   ]
  },
  {
   "title": "Request duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path, method) (rate(request_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "{{method}}:{{path}}"
    }
   ]
  }
 ]
}